//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public int IdRole { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public string SeriaPasporta { get; set; }
        public string NomerPasporta { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<System.DateTime> LastEntry { get; set; }
        public Nullable<bool> TypeEntry { get; set; }
        public int idGender { get; set; }
    
        public virtual UserGender UserGender { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
